// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VismaBugBountySelfServicePortal.Database;

namespace VismaBugBountySelfServicePortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210929070919_AddAssetPrograms")]
    partial class AddAssetPrograms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VismaBugBountySelfServicePortal.Models.Entity.AssetEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AssetName");

                    b.Property<string>("Columns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnHackerOne")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnPublicProgram")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Programs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("VismaBugBountySelfServicePortal.Models.Entity.CredentialEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SetId");

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HackerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Transferred")
                        .HasColumnType("bit");

                    b.HasKey("Key", "AssetName");

                    b.ToTable("Credential");
                });

            modelBuilder.Entity("VismaBugBountySelfServicePortal.Models.Entity.CredentialValueEntity", b =>
                {
                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SetId");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("ColumnName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColumnValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetName", "Key", "RowNumber", "ColumnName");

                    b.ToTable("CredentialValue");
                });

            modelBuilder.Entity("VismaBugBountySelfServicePortal.Models.Entity.RequestCredentialHistoryEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SetId");

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HackerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Key", "AssetName", "HackerName");

                    b.ToTable("RequestCredentialHistory");
                });

            modelBuilder.Entity("VismaBugBountySelfServicePortal.Models.Entity.TransferCredentialHistoryEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FromEmail");

                    b.Property<string>("ToEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TransferredDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Key", "ToEmail");

                    b.ToTable("TransferCredentialHistory");
                });

            modelBuilder.Entity("VismaBugBountySelfServicePortal.Models.Entity.UserEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");

                    b.HasKey("Key");

                    b.ToTable("User");
                });

            modelBuilder.Entity("VismaBugBountySelfServicePortal.Models.Entity.UserSessionEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Key", "SessionId");

                    b.ToTable("UserSession");
                });

            modelBuilder.Entity("VismaBugBountySelfServicePortal.Models.Entity.UserSessionHistoryEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Key", "SessionId");

                    b.ToTable("UserSessionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
